# Generated by Django 2.0.3 on 2018-03-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='Post',
        ),
    ]
